######: https://github.com/guichengpeng1
######:Chengpeng.Gui@uhn.ca
library(forestplot)
result <- read.csv("//Volumes//AI//Indep.csv",header = FALSE)
fig <- forestplot(result[,c(1:4,8:9)],           
                  mean=result[,5],
                  lower=result[,6],
                  upper=result[,7],
                  zero=1,                        
                  boxsize=0.6,
                  graph.pos = 5,
                  graph.width = unit(160,"mm"),
                  hrzl_lines=list('1'=gpar(lty=1,lwd=2),
                                  '2'=gpar(lty=2),
                                  '19'=gpar(lwd=1,lty=1)),      
                  graphwidth=unit(.25,'npc'),
                  xticks=c(1,2,5,10,20),                           
                  is.summary=c(T,
                               T,F,F,
                               T,F,F,
                               T,F,F,F,
                               T,F,F,
                               T,F,F,
                               T,F,F,
                               T,F,F,F,F,
                               T,F,F,
                               F,F,F,
                               T,F,F,F),                        
                  txt_gp=fpTxtGp(label = gpar(cex=1),
                                 ticks = gpar(cex=1.1),
                                 xlab = gpar(cex=1),
                                 title = gpar(cex=2)),
                  lwd.zero=2,
                  lwd.ci=2,
                  lwd.xaxis=1,xlab='Hazard ratio',               
                  lty.ci=1,
                  ci.vertices=T,
                  ci.vertices.height=0.2,
                  clip=c(0,4),
                  ineheight=unit(8,'mm'),
                  line.margin=unit(8,'mm'),
                  colgap=unit(6,'mm'),
                  col=fpColors(zero = 'black',
                               box = 'black',
                               lines = 'black'),
                  fn.ci_norm='fpDrawCircleCI'
)
fig
######: https://github.com/guichengpeng1
######:Chengpeng.Gui@uhn.ca
